Fixes #141: Handle node
utnaf/neo4j-spark-connector pull request #3
Opened 2020-07-17 14:24 UTC by utnaf

2020-07-17 18:09 UTC, conker84 requested changes
per favore guarda i miei commenti

2020-07-17 18:09 UTC, conker84 commented on pom.xml
> +            <version>2020.0.0</version>
lo parametrizziamo?

2020-07-17 18:09 UTC, conker84 commented on src/main/scala/org/neo4j/spark/service/SchemaService.scala
> +      case "LocalDateArray" | "DateArray" => DataTypes.createArrayType(DataTypes.DateType)
manca la gestione di duration e array di duration:
https://neo4j.com/docs/cypher-manual/4.1/syntax/values/
e
https://neo4j.com/docs/cypher-manual/current/functions/temporal/duration/

2020-07-17 18:09 UTC, conker84 commented on src/main/scala/org/neo4j/spark/DriverCache.scala
> +  private val idCache = new ConcurrentHashMap[String, Boolean]
```suggestion
  private val jobIdCache = new ConcurrentHashMap[String, Boolean]
```

2020-07-17 18:09 UTC, conker84 commented on src/main/scala/org/neo4j/spark/reader/Neo4jDataSourceReader.scala
> +    factoryList.add(new Neo4jInputPartitionReader(neo4jOptions, readSchema(), jobId))
salviamo read-schema in una variabile ci sarà utili quando dovremo istanziare più `Neo4jInputPartitionReader`

2020-07-17 18:09 UTC, conker84 commented on src/main/scala/org/neo4j/spark/reader/Neo4jInputPartitionReader.scala
> +  var customIterator: Iterator[Record] = _
```suggestion
  var result: Result = _
  var transaction: Transaction = _
```

2020-07-17 18:09 UTC, conker84 commented on src/main/scala/org/neo4j/spark/reader/Neo4jInputPartitionReader.scala
> +  }
la gestione della transaction la dobbiamo fare subito altrimenti ce lo cassano:
```suggestion
  def next: Boolean = {
    if (result == null) {
      session = driverCache.getOrCreate().session(options.session.toNeo4jSession()) // crea il metodo
      transaction = session.beginTransaction()
      result = transaction.run(Neo4jQuery.build(options.query))
    }
    result.hasNext
  }
```

2020-07-17 18:09 UTC, conker84 commented on src/main/scala/org/neo4j/spark/reader/Neo4jInputPartitionReader.scala
> +  def convertFromSpark(value: Any): Any = value match {
```suggestion
  def convertFromNeo4j(value: Any): Any = value match {
```

2020-07-17 18:09 UTC, conker84 commented on src/main/scala/org/neo4j/spark/reader/Neo4jInputPartitionReader.scala
> +    Neo4jUtil.closeSafety(session)
```suggestion
    Neo4jUtil.closeSafety(transaction)
    Neo4jUtil.closeSafety(session)
```

2020-07-17 18:09 UTC, conker84 commented on src/main/scala/org/neo4j/spark/service/SchemaService.scala
> +  private def mapType(internalType: String): DataType = {
```suggestion
  private def cypherToSparkType(cypherType: String): DataType = {
```

2020-07-17 18:09 UTC, conker84 commented on src/main/scala/org/neo4j/spark/util/Neo4jUtil.scala
> +        case s: Session => if (s.isOpen) s.close()
```suggestion
        case s: Session => if (s.isOpen) s.close()
        case t: Transaction => if (t.isOpen) t.close()
```

2020-07-17 18:09 UTC, conker84 commented on src/test/scala/org/neo4j/spark/DataSourceApocIT.scala
> +    assertEquals(44.222, res(1).get(2))
manca il terzo elemento, la `z`

2020-07-17 18:09 UTC, conker84 commented on src/test/scala/org/neo4j/spark/DataSourceApocIT.scala
> +    assertEquals(100, numNode)
aggiungiamo un controllo sui nome dei campi

2020-07-17 18:09 UTC, conker84 commented on src/test/scala/org/neo4j/spark/DataSourceApocIT.scala
> +class DataSourceApocIT extends SparkConnectorScalaBaseApocTSE {
Nb, i punti hai solo fatto i test per le coordinate cartesiane, aggiungi quelle geografiche per favore:
https://neo4j.com/docs/cypher-manual/current/syntax/spatial/#cypher-spatial-crs-geographic

2020-07-17 18:09 UTC, conker84 commented on src/main/scala/org/neo4j/spark/reader/Neo4jInputPartitionReader.scala
> +  }
@utnaf ricordami che dobbiamo parlare dell'accessMode lo dobbiamo mettere subito poi ti spiego perché

2020-07-17 18:12 UTC, conker84 commented
@utnaf dobbiamo anche cambiare la gestione dei test dobbiamo renderla più flessibile adesso è fissata su "Person" e non c'è un test sulla selezione del database.
Non c'è un test multi label, dobbiamo aggiungerlo.
Non c'è un test con due dataframe che vanno su dataset database diversi e poi fa la join dei due... dobbiamo aggiungerlo.

2020-07-20 08:05 UTC, utnaf commented on src/test/scala/org/neo4j/spark/DataSourceApocIT.scala
> +    assertEquals(100, numNode)
in che senso?

2020-07-21 10:30 UTC, conker84 requested changes
manca solo la documentazione e questa cavolta per il resto ci siamo grazie mille!

2020-07-21 10:30 UTC, conker84 commented on src/test/scala/org/neo4j/spark/SparkConnectorScalaSuiteNoApocIT.scala
> +        .set("spark.neo4j.url", SparkConnectorScalaSuiteNoApocIT.server.getBoltUrl)
per favore cancella questa che non ci serve, anche nel test con le apoc per favore

2020-07-22 15:46 UTC, conker84 requested changes
grazie Davide per favore guarda i commenti

2020-07-22 15:46 UTC, conker84 commented on doc/docs/modules/ROOT/pages/v2.adoc
> += Quick Start
elimina questo file e metti tutto dentro quickstart.adoc

2020-07-22 15:46 UTC, conker84 commented on doc/docs/modules/ROOT/pages/v2.adoc
> +Remember that the first Label is considered to be the primary label.
```suggestion
[NOTE]
Remember that the first Label is considered to be the primary label.
```

2020-07-22 15:46 UTC, conker84 commented on doc/docs/modules/ROOT/pages/v2.adoc
> +TK Overview
Scrivici due righe due senno ce le fa mettere lui

2020-07-22 15:46 UTC, conker84 commented on doc/docs/modules/ROOT/pages/v2.adoc
> +TK Provide short description of the example code
Anche qui

2020-07-22 15:46 UTC, conker84 commented on doc/docs/modules/ROOT/pages/v2.adoc
> +        .option("node.labels", "Person")
dovrebbe essere così:
```suggestion
        .option("labels", "Person")
```

2020-07-22 15:46 UTC, conker84 commented on doc/docs/modules/ROOT/pages/v2.adoc
> +        .option("node.labels", "Person")
come sopra

2020-07-22 15:46 UTC, conker84 commented on doc/docs/modules/ROOT/pages/v2.adoc
> +When reading data with this method, the result set will contain all the columns contained in the nodes, plus 2 additional columns.
```suggestion
When reading data with this method, the Dataframe will contain all the fields contained in the nodes, plus 2 additional columns.
```

cerchiamo di usare i termini di Spark/Neo4j

2020-07-22 15:46 UTC, conker84 commented on src/main/scala/org/neo4j/spark/reader/Neo4jInputPartitionReader.scala
> +  var driverCache: DriverCache = new DriverCache(options.connection, jobId)
mettiamoli privati

2020-07-22 15:46 UTC, conker84 commented on src/main/scala/org/neo4j/spark/service/SchemaService.scala
> +      })
mettiamolo in un metodo `retrieveSchemaFromApoc`

2020-07-22 15:46 UTC, conker84 commented on src/main/scala/org/neo4j/spark/service/SchemaService.scala
> +    StructType(structFields.reverse)
mettiamolo in un metodo `retrieveSchema`

2020-07-22 15:46 UTC, conker84 commented on src/main/scala/org/neo4j/spark/service/SchemaService.scala
> +      case "LocalDateTime" | "DateTime" | "ZonedDateTime" | "OffsetTime" | "Time" => DataTypes.TimestampType
OffsetTime, Time e secondo me c'è anche LocalTime non docrebbero essere struct come avevamo detto?

2020-07-22 15:46 UTC, conker84 commented on src/main/scala/org/neo4j/spark/service/SchemaService.scala
> +object SchemaService {
manca la struct per il time

2020-07-22 15:46 UTC, conker84 commented on src/main/scala/org/neo4j/spark/service/SchemaService.scala
> +  val POINT_TYPE_3D = "point-3d"
a che servono?

2020-07-22 15:46 UTC, conker84 commented on src/main/scala/org/neo4j/spark/util/Neo4jUtil.scala
> +    case d: InternalIsoDuration =>
mettiamo delle graffe così diventa più leggibile

2020-07-22 15:46 UTC, conker84 commented on src/main/scala/org/neo4j/spark/util/Neo4jUtil.scala
> +    case p: InternalPoint2D =>
graffe

2020-07-22 15:46 UTC, conker84 commented on src/main/scala/org/neo4j/spark/util/Neo4jUtil.scala
> +    case lt: LocalTime => UTF8String.fromString(lt.format(DateTimeFormatter.ISO_TIME))
avevamo detto struct

2020-07-22 15:46 UTC, conker84 commented on src/main/scala/org/neo4j/spark/util/Neo4jUtil.scala
> +    case lt: LocalTime => UTF8String.fromString(lt.format(DateTimeFormatter.ISO_TIME))
perché poi serve a me per fare l'ingestion

2020-07-22 15:54 UTC, utnaf commented on src/main/scala/org/neo4j/spark/service/SchemaService.scala
> +object SchemaService {
l'ho gestito come stringa e basta, come ti dicevo

2020-07-22 16:00 UTC, utnaf commented on src/main/scala/org/neo4j/spark/service/SchemaService.scala
> +      case "LocalDateTime" | "DateTime" | "ZonedDateTime" | "OffsetTime" | "Time" => DataTypes.TimestampType
Ok chiaro, modifico asap

2020-07-22 16:01 UTC, utnaf commented on src/main/scala/org/neo4j/spark/service/SchemaService.scala
> +  val POINT_TYPE_3D = "point-3d"
vengono usate per creare il campo Point, vedi Neo4jUtils

2020-07-22 16:02 UTC, utnaf commented on src/main/scala/org/neo4j/spark/util/Neo4jUtil.scala
> +    case lt: LocalTime => UTF8String.fromString(lt.format(DateTimeFormatter.ISO_TIME))
si ho dimenticato queste struct

2020-07-23 09:28 UTC, conker84 requested changes
Queste ultime cose e ci siamo. Sono solo dettagli, occhio che rinominando le classi ti rinomini anche i file a me non so perché non l'ha fatto...
Grazie mille!!!

2020-07-23 09:28 UTC, conker84 commented on doc/docs/modules/ROOT/pages/quickstart.adoc
> +|location|Point
per favore aggiungi un paragrafo su come gestiamo i data type particolari, così diamo evidenza a David

2020-07-23 09:28 UTC, conker84 commented on src/test/scala/org/neo4j/spark/SparkConnectorScalaBaseApocTSE.scala
> +object SparkConnectorScalaBaseApocTSE {
```suggestion
object SparkConnectorScalaBaseWithApocTSE {
```

2020-07-23 09:28 UTC, conker84 commented on src/test/scala/org/neo4j/spark/SparkConnectorScalaBaseNoApocTSE.scala
> +object SparkConnectorScalaBaseNoApocTSE {
```suggestion
object SparkConnectorScalaBaseTSE {
```

2020-07-23 09:28 UTC, conker84 commented on src/test/scala/org/neo4j/spark/SparkConnectorScalaSuiteApocIT.scala
> +object SparkConnectorScalaSuiteApocIT {
```suggestion
object SparkConnectorScalaSuiteWithApocIT {
```

2020-07-23 09:28 UTC, conker84 commented on src/test/scala/org/neo4j/spark/SparkConnectorScalaSuiteNoApocIT.scala
> +object SparkConnectorScalaSuiteNoApocIT {
```suggestion
object SparkConnectorScalaSuiteIT {
```

2020-07-23 09:28 UTC, conker84 commented on src/test/scala/org/neo4j/spark/service/SchemaServiceApocModeIT.scala
> +class SchemaServiceApocModeIT extends SparkConnectorScalaBaseApocTSE {
```suggestion
class SchemaServiceWithApocIT extends SparkConnectorScalaBaseWithApocTSE {
```

2020-07-23 09:28 UTC, conker84 commented on src/test/scala/org/neo4j/spark/service/SchemaServiceNoApocModeIT.scala
> +class SchemaServiceNoApocModeIT extends SparkConnectorScalaBaseNoApocTSE {
```suggestion
class SchemaServiceIT extends SparkConnectorScalaBaseTSE {
```

2020-07-23 09:28 UTC, conker84 commented on src/test/scala/org/neo4j/spark/DataSourceApocIT.scala
> +class DataSourceApocIT extends SparkConnectorScalaBaseApocTSE {
```suggestion
class DataSourceReaderWithApocIT extends SparkConnectorScalaBaseWithApocTSE {
```

2020-07-23 09:28 UTC, conker84 commented on src/test/scala/org/neo4j/spark/DataSourceNoApocIT.scala
> +class DataSourceNoApocIT extends SparkConnectorScalaBaseNoApocTSE {
```suggestion
class DataSourceReaderIT extends SparkConnectorScalaBaseTSE {
```

2020-08-07 09:04 UTC, merged