Issue 145
utnaf/neo4j-spark-connector pull request #5
Opened 2020-08-12 14:38 UTC by utnaf

2020-08-13 09:29 UTC, conker84 requested changes
Ci sono ancora delle cose che non mi sono chiare, devo capire come funziona nel caso `NATIVE` la generazione delle query, perché per me le `keys` sono necessarie in funzione della `relationship.<source/target>.save.mode` perché altrimenti rischiamo di duplicare i nodi anche nel caso di `Overwrite`
Dobbiamo rivederlo bene insieme

2020-08-13 09:29 UTC, conker84 commented on doc/docs/modules/ROOT/pages/quickstart.adoc
> +|`relationship.access.mode`
credo sia?
```suggestion
|`relationship.write.strategy`
```

2020-08-13 09:29 UTC, conker84 commented on doc/docs/modules/ROOT/pages/quickstart.adoc
> +|No
```suggestion
|`relationship.target.save.mode`
|<<node-save-modes,Node Save Mode>>
|`Match`
|No
```

2020-08-13 09:29 UTC, conker84 commented on doc/docs/modules/ROOT/pages/quickstart.adoc
> +|No
```suggestion
|`relationship.source.save.mode`
|<<node-save-modes,Node Save Mode>>
|`Match`
|No
```

2020-08-13 09:29 UTC, conker84 commented on src/main/scala/org/neo4j/spark/Neo4jOptions.scala
> +    }
E' necessaria questa validazione qui?
Non possiamo metterla dentro `Validations`?

2020-08-13 09:29 UTC, conker84 commented on src/main/scala/org/neo4j/spark/Neo4jOptions.scala
> +      .find(_.toString == getParameter(RELATIONSHIP_WRITE_STRATEGY, DEFAULT_RELATIONSHIP_WRITE_STRATEGY.toString).toUpperCase)
```suggestion
    val writeStrategy = RelationshipWriteStrategy.withName(getParameter(RELATIONSHIP_WRITE_STRATEGY, DEFAULT_RELATIONSHIP_WRITE_STRATEGY.toString).toUpperCase)
```

e togli la validazione sotto

2020-08-13 09:29 UTC, conker84 commented on src/main/scala/org/neo4j/spark/Neo4jOptions.scala
> +    }
Anche quì usa `NodeSaveMode.withName` come sopra e togli l'if

2020-08-13 09:29 UTC, conker84 commented on src/main/scala/org/neo4j/spark/Neo4jOptions.scala
> +    }
come sopra

2020-08-13 09:29 UTC, conker84 commented on src/main/scala/org/neo4j/spark/Neo4jOptions.scala
> +  val RELATIONSHIP_SOURCE_SAVE_MODE = s"${QueryType.RELATIONSHIP.toString.toLowerCase}.source.$ACCESS_MODE"
questo è sbagliato
```suggestion
  val RELATIONSHIP_SOURCE_SAVE_MODE = s"${QueryType.RELATIONSHIP.toString.toLowerCase}.source.save.mode"
```

2020-08-13 09:29 UTC, conker84 commented on src/main/scala/org/neo4j/spark/Neo4jOptions.scala
> +  val RELATIONSHIP_TARGET_SAVE_MODE = s"${QueryType.RELATIONSHIP.toString.toLowerCase}.target.$ACCESS_MODE"
```suggestion
  val RELATIONSHIP_TARGET_SAVE_MODE = s"${QueryType.RELATIONSHIP.toString.toLowerCase}.target.save.mode"
```

2020-08-13 09:29 UTC, conker84 commented on doc/docs/modules/ROOT/pages/quickstart.adoc
> +|`relationship.access.mode`
Tra l'altro va documentato bene cosa succede con le differenti strategy

2020-08-13 09:29 UTC, conker84 commented on doc/docs/modules/ROOT/pages/quickstart.adoc
> +```
va spiegato cosa generiamo, `experience` immagino vada a finire come proprietà della relazione `PLAYS` giusto?

2020-08-13 09:29 UTC, conker84 commented on src/main/scala/org/neo4j/spark/service/MappingService.scala
> +          }
manca l'else?

2020-08-13 09:29 UTC, conker84 commented on src/test/scala/org/neo4j/spark/DataSourceWriterTSE.scala
> +  def `should read relations and write relation`(): Unit = {
```suggestion
  def `should read and write relations`(): Unit = {
```

2020-08-26 09:31 UTC, conker84 requested changes
giusto delle cavolate ottimo grazie

2020-08-26 09:31 UTC, conker84 commented on src/main/scala/org/neo4j/spark/Neo4jOptions.scala
> +  val WRITE_MODE = "write.mode"
solo per essere aderente alla terminologia di Spark
```suggestion
  val SAVE_MODE = "save.mode"
```

2020-08-26 09:31 UTC, conker84 commented on src/main/scala/org/neo4j/spark/Neo4jOptions.scala
> +  val RELATIONSHIP_WRITE_STRATEGY = s"${QueryType.RELATIONSHIP.toString.toLowerCase}.write.strategy"
solo per essere aderente alla terminologia di Spark
```suggestion
  val RELATIONSHIP_SAVE_STRATEGY = s"${QueryType.RELATIONSHIP.toString.toLowerCase}.save.strategy"
```

2020-08-26 09:31 UTC, conker84 commented on src/main/scala/org/neo4j/spark/Neo4jOptions.scala
> +object RelationshipWriteStrategy extends Enumeration {
```suggestion
object RelationshipSaveStrategy extends Enumeration {
```

2020-08-26 09:31 UTC, conker84 commented on src/main/scala/org/neo4j/spark/Neo4jOptions.scala
> +object NodeWriteMode extends Enumeration {
```suggestion
object NodeSaveMode extends Enumeration {
```

2020-08-26 09:31 UTC, conker84 commented on src/main/scala/org/neo4j/spark/service/MappingService.scala
> +    val sourceMap = new util.HashMap[String, util.Map[String, AnyRef]]()
```suggestion
    val sourceNodeMap = new util.HashMap[String, util.Map[String, AnyRef]]()
```

2020-08-26 09:31 UTC, conker84 commented on src/main/scala/org/neo4j/spark/service/MappingService.scala
> +    val targetMap = new util.HashMap[String, util.Map[String, AnyRef]]()
```suggestion
    val targetNodeMap = new util.HashMap[String, util.Map[String, AnyRef]]()
```

2020-08-26 09:31 UTC, conker84 commented on src/test/scala/org/neo4j/spark/DataSourceWriterTSE.scala
> +        })
possono essere unite in un unica write transaction

2020-08-26 09:31 UTC, conker84 commented on src/test/scala/org/neo4j/spark/DataSourceWriterTSE.scala
> +    assertEquals(df1count, df2count)
puoi aggiungere una comparazione sui nodi sorgenti e destinazione?

2020-08-26 09:31 UTC, conker84 commented on src/test/scala/org/neo4j/spark/DataSourceWriterTSE.scala
> +        })
come sopra

2020-08-26 09:31 UTC, conker84 commented on src/test/scala/org/neo4j/spark/DataSourceWriterTSE.scala
> +        })
come sopra

2020-08-26 09:31 UTC, conker84 commented on src/test/scala/org/neo4j/spark/DataSourceWriterTSE.scala
> +      .option("relationship.target.node.keys", "id:target.id")
questo non dovrebbe essere al contrario?
(dal dataframe-> al grafo)
```suggestion
      .option("relationship.source.node.keys", "source.id:id")
      .option("relationship.target.node.keys", "target.id:id")
```

2020-08-26 09:31 UTC, conker84 commented on src/test/scala/org/neo4j/spark/DataSourceWriterTSE.scala
> +    assertEquals(df1count, df2count)
anche qui se fosse possibile fare un confronto tra source e target?

2020-08-26 09:31 UTC, conker84 commented on src/test/scala/org/neo4j/spark/DataSourceWriterTSE.scala
> +        })
come sopra

2020-08-26 09:31 UTC, conker84 commented on src/test/scala/org/neo4j/spark/DataSourceWriterTSE.scala
> +      .option("relationship.target.write.mode", "Overwrite")
mapping al contrario

2020-08-26 09:31 UTC, conker84 commented on src/test/scala/org/neo4j/spark/DataSourceWriterTSE.scala
> +      .option("relationship.source.write.mode", "Match")
Domanda qual'è la save mode di default per i nodi? Per favore metti `Match`

2020-08-26 13:16 UTC, utnaf commented on src/test/scala/org/neo4j/spark/DataSourceWriterTSE.scala
> +      .option("relationship.source.write.mode", "Match")
Default è la `Match`

2020-08-26 14:04 UTC, conker84 requested changes
Giusto due cavolate

2020-08-26 14:04 UTC, conker84 commented on src/main/scala/org/neo4j/spark/service/Neo4jQueryService.scala
> +       |${createQueryPart(sourceKeyword, sourceLabels, sourceKeys, Neo4jUtil.RELATIONSHIP_SOURCE_ALIAS)}
puoi mettere questa e la chiamata successiva in due variabili `sourceQueryPart` & `targetQueryPart`?

2020-08-26 14:04 UTC, conker84 commented on src/main/scala/org/neo4j/spark/writer/Neo4jDataWriter.scala
> +      log.info(s"Writing batch into Neo4j with query: $query")
uniscili per favore

2020-08-26 15:07 UTC, conker84 requested changes
dopo di questo abbiamo fatto

2020-08-26 15:07 UTC, conker84 commented on src/main/scala/org/neo4j/spark/writer/Neo4jDataWriter.scala
> +           |""".stripMargin)
```suggestion
        s"""Writing a batch of ${batch.size()} elements to Neo4j, 
           |for jobId=$jobId and partitionId=$partitionId 
           |with query: $query""".stripMargin)
```

2020-08-26 15:07 UTC, conker84 commented on src/main/scala/org/neo4j/spark/service/Neo4jQueryService.scala
> +    }
possiamo fare una funzione e riusare quella per i due casi?

2020-08-26 15:07 UTC, conker84 commented on src/main/scala/org/neo4j/spark/service/Neo4jQueryService.scala
> +       |SET ${Neo4jUtil.RELATIONSHIP_ALIAS} = $BATCH_VARIABLE.${Neo4jUtil.RELATIONSHIP_ALIAS}.${Neo4jWriteMappingStrategy.PROPERTIES}
io ricordo c'era il `+`, comunque (ri)mettilo
```suggestion
       |SET ${Neo4jUtil.RELATIONSHIP_ALIAS} += $BATCH_VARIABLE.${Neo4jUtil.RELATIONSHIP_ALIAS}.${Neo4jWriteMappingStrategy.PROPERTIES}
```

2020-08-26 15:07 UTC, conker84 commented on src/test/scala/org/neo4j/spark/DataSourceWriterTSE.scala
> +    )
cosi lo facciamo solo per il primo, possiamo fare un ciclo che lo controlla per ogni riga?

2020-08-26 15:07 UTC, conker84 commented on src/test/scala/org/neo4j/spark/DataSourceWriterTSE.scala
> +    )
come sopra

2020-08-26 15:07 UTC, conker84 commented on src/test/scala/org/neo4j/spark/DataSourceWriterTSE.scala
> +    )
come sopra

2020-08-28 09:20 UTC, closed without merging